### PR TITLE
718 refactor vault downloads

### PR DESCRIPTION
**Pull request by Wesmania**
This code refactors downloading assets from the vault. It adds the following:

- FileDownload class for convenient download of files from a url,
- VaultDownloadDialog for presenting a modal dialog while downloading a file
- downloadVaultAsset function that uses both of the above to download a file, do logging and present other modal windows to the user,
- refactored downloadMap and downloadMod that use the above.

These changes should make adding support for downloading tutorials easy.

I'd like comments on the FileDownload class - there's some complex interactions with QNetworkReply signals that feel non-obvious and seem hard to unit test.

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Brutus5000** [comment]
I don't know whether it's a specific Qt4 thing, but the downloader seems to do quite unnecessary low level stuff. I.e. do we care about the number of redirects? Qt should notice an infinite loop.
For a minimal Qt5 downloader see [here](https://github.com/Brutus5000/BiReUS-Launcher/blob/master/launcher/download_service.py).

I'd suggest using signals to broadcast any changes of the downloader so you can listen to the events from anywhere (and any thread). Decoupling a service using signal/slots is one of the core ideas behind Qt.

**Comment by duk3luk3** [comment]
> I don't know whether it's a specific Qt4 thing, but the downloader seems to do quite unnecessary low level stuff. I.e. do we care about the number of redirects? Qt should notice an infinite loop.

Qt4 NetworkAccessManager doesn't handle redirects.

**Comment by Wesmania** [comment]
Thanks for the link to the downloader brutus, I see a couple of thing that will simplify stuff a lot (didn't notice that downloadProgress signal, for example).

**Comment by Wesmania** [comment]
We can simplify FileDownload code by a lot if we don't bother with redirects just yet. The original code used requests, and it follows redirects, but it's only used to access files in the vault, and I haven't seen any redirects there. I think we can stomach no redirect support until we get to qt5.

**Comment by duk3luk3** [comment]
As soon as we do something sensible on the server like enforce https, there will be redirects.

**Pull request merged**
