### PR TITLE
feature - single line the layout of modvault

### PR DESCRIPTION
**Pull request by GrotheFAF**
put all textboxes and buttons in a single line
https://github.com/FAForever/client/pull/499/commits/c05349f7d5f2e4822960861eb484206a5ece7e95 remove empty/obsolete layout elements

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [x] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
What does this PR do?

**Comment by GrotheFAF** [comment]
added description.

**Comment by GrotheFAF** [comment]
updated description

**Comment by Wesmania** [comment]
It seems plenty of lines are ugly unrelated changes that were introduced by qtdesigner. @duk3luk3, I don't think anyone opens ui files with anything but designer, and you can't reduce that second commit to less lines since there's indentation changes. I think it can get pulled, maybe after removing some of the unneeded width/size property changes?

**Comment by GrotheFAF** [comment]
These 'width/size property changes' are not 'unneeded', they there to make it look good.
Try it in your VM and **see** for yourself.

**Comment by GrotheFAF** [comment]
so I guess I can delete this too?

**Pull request closed without merging**
