### PR TITLE
Add pwning to client

### PR DESCRIPTION
**Pull request by HardlySoftly**
Server will be able to remotely pwn the client by sending the json
object:
{"command": "pwning", "pwned": 1}
and unpwn with:
{"command": "pwning", "pwned": 0}

### CODE REVIEW

**Comment by VoRGoR** [comment]
Definitely a required feature.

**Comment by aeoncleanse** [comment]
Sooo yeah, this needs to happen :D :+1:

**Comment by HardlySoftly** [comment]
To clarify, pwning involves reversing all their text, or replacing it with "kick me"

**Comment by Sheeo** [comment]
I'm sorry, but I don't see any improvement in this pull request. Are you serious @VoRGoR and @aeoncleanse that you want to see this implemented?

**Comment by aeoncleanse** [comment]
I was only half-serious, hardly know what it does. Messes with chat or something fun?

**Comment by Sheeo** [comment]
Yes. I'm closing this for now.

**Pull request closed without merging**
