### PR TITLE
feature - change to flat style

### PR DESCRIPTION
**Pull request by GrotheFAF**
affects dropdownboxes and pushbuttons:
Tab Play: Sort Games, 
Tab Replay: Search: Mod, Min. Rating, Refresh Recent List, Search
Tab Vaults: Mods: everything  on top (except searchinput)
Host Game: Map
FA bottom: Ladder offer.

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [x] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
Which elements does this change?

**Comment by GrotheFAF** [comment]
added description.

**Comment by GrotheFAF** [comment]
updated description.

**Comment by GrotheFAF** [comment]
Try it in your VM and see for yourself.

**Comment by GrotheFAF** [comment]
so I guess I can delete this too?

**Pull request closed without merging**
