### PR TITLE
Replay vault ui panels

### PR DESCRIPTION
**Pull request by TimWolters**
Changed ui in the Replayvault. [(screen1)](http://puu.sh/o74Nk/e36423d0e1.jpg)[(screen2)](http://puu.sh/o75oH/2bb4d63955.jpg) 
Split generateInfoPlayersHtml into different methods .
Moved html as much as possible to the top and in constants.
Added free-for-all in the extra information of the replay.
Removed observers from the extra information of the replay.
Removed after rating from extra information of the replay (in code).

Did some things on things on the ReplayVault.
I'm not sure what you think of the ui but I'm happy to hear your reaction about it (or put it up on the forum for ideas on improvement)/discard it. 
The reason why I didn't put the html into files is the amount of new files with 3 or 4 lines of html in it.

Implementing: #316

### CODE REVIEW

**Comment by Sheeo** [comment]
Hey, sorry to not review this sooner. Looks good! Would you mind rebasing onto the latest develop so we can get this into 0.11.59?

**Comment by Sheeo** [comment]
screenshot 2016-06-01 12 47 48

Is the checkbox for spoilers meant to look like this, or is it only on my high dpi display that this happens?

**Comment by TimWolters** [comment]
That's not supposed to happen. I've taken a look at it but I'm not able to reproduce it. It's like the spoiler checkbox doesn't have the minimum size of 80.  I know you have it busy but if you have the time, could you take a look in res/replays/replays.ui and look if it's the same there?

**Comment by Crotalus** [comment]
Rebased to #392

**Pull request closed without merging**
