### PR TITLE
fix #694 chat user 'View Replays in Vault' does not reset Mod

### LINKED ISSUE #694: chat user 'View Replays in Vault' does not reset Mod
If a Mod (different from 'All') is set in Replays Search, 'View Replays in Vault' from Chat Lobby doesn't rest that to 'All'.
(This could be considered a feature in some cases, but normally one expects all recent replays of a user)

### PR DESCRIPTION
**Pull request by GrotheFAF**
add set modList to index(0) 'All'

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
Please add a changelog entry.

**Comment by GrotheFAF** [comment]
added changelog
(and corrected changelog for #686)

**Comment by duk3luk3** [comment]
Please rebase this again - sorry!

**Comment by GrotheFAF** [comment]
it is allready, isn't it?

**Comment by duk3luk3** [comment]
Yeah, I got confused. sorry.

**Pull request merged**
