### PR TITLE
add Themes folder to Menu-Options-Show Paths...

### PR DESCRIPTION
**Pull request by GrotheFAF**
as with recent Theme break thought this come in handy

### CODE REVIEW

**Comment by duk3luk3** [comment]
I don't see a reason not to put this in.

**Comment by Wesmania** [comment]
There's some unnecessary spam introduced by the designer in the diff (margin replaced by 4 different margins, height randomly changed from 22 to 18), please fix it first.

**Comment by GrotheFAF** [comment]
done

**Comment by Wesmania** [comment]
Okay, rebase and I'll merge. It's user-visible too, so add a changelog entry if you want.

**Comment by GrotheFAF** [comment]
done

**Comment by Wesmania** [comment]
Please put the changelog under 0.16.0 :)

**Comment by GrotheFAF** [comment]
done

**Pull request merged**
