### PR TITLE
Use the new uid implementation

### PR DESCRIPTION
**Pull request by muellni**
This PR requires https://github.com/FAForever/server/pull/121 on the server!
The client now needs the prebuilt binary Python module from https://github.com/muellni/uid/releases .

### CODE REVIEW

**Comment by Sheeo** [comment]
This appears to fail on both CI's -- the `uid` package isn't being installed on any of them.

**Comment by muellni** [comment]
> This appears to fail on both CI's -- the uid package isn't being installed on any of them.

The `uid` module is currently not part of the client. I've uploaded prebuilt binaries to https://github.com/muellni/uid/releases

**Comment by Sheeo** [comment]
To make CI not break you'll need to get it to download it during the build process, then.

**Comment by ChrisKitching** [comment]
This has been merged successfully into the `pyqt5` branch. It may or may not be actually merged into develop on its own before pyqt5 makes its way there.

Thanks for the excellent work. Very glad to be rid of that awful binary, and to be able to do a proper 64 bit build.

**Comment by ChrisKitching** [comment]
Since this has merged (although not quite yet into develop) I guess we can close this to get it out of the way.

Thanks again for saving us from that awful binary :D

**Pull request closed without merging**
