### PR TITLE
Add manifest

### PR DESCRIPTION
**Pull request by duk3luk3**
Add manifest to keep windows from automatically elevating FAF.

For #487. 

Initial PR:

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
@muellni did I add the manifest file correctly to `setup.py`?

**Comment by muellni** [comment]
@duk3luk3 IDK. I have close to zero experience with manifest files, but I thought the file is compiled/linked into the exe.

**Comment by muellni** [comment]
I checked http://superuser.com/a/396764 and it looks ok like that. But it states that you have to check that the exe does not already have an embedded manifest, because the external would be ignored.
This elevation thing looks like a snakepit...

**Comment by duk3luk3** [comment]
I assumed that cx_Freeze / bdist_msi doesn't compile manifests into the exe.

**Comment by muellni** [comment]
Apparently it does for Python 2 msvcrt. `sigcheck.exe -m FAForever.exe:`
```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedE
xecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC90.CRT" version="9.0.2102
2.8" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIde
ntity>
    </dependentAssembly>
  </dependency>
</assembly>
```

**Comment by duk3luk3** [comment]
So it already has `asInvoker`... well that's a bummer :/

**Comment by duk3luk3** [comment]
Another way to try here: http://superuser.com/a/450503

**Pull request closed without merging**
