### PR TITLE
Remove supcom linking from coop

### PR DESCRIPTION
**Pull request by Wesmania**
Since we no longer need the original supcom to play vanilla campaigns,
remove linking of original supcom.

Signed-off-by: Igor Kotrasinski <ikotrasinsk@gmail.com>

Thank you for contributing to this project! Please set a good title for your PR and  replace this line with a (preferrably multi-line) description of your PR.

Please check these boxes as you make your PR ready for merging:

Initial PR:

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Wesmania** [comment]
Did you test this one, @speed2CZ ?

**Comment by speed2CZ** [comment]
I dont know how to test it

**Comment by Wesmania** [comment]
Making sure there's no trace of vanilla supcom links in the client (like running from fresh config and no coop downloaded) then trying to run a vanilla mission should be enough. I really want to make sure linking is not needed.
BTW out of curiosity, if we don't need vanilla supcom anymore, does it mean we're distributing assets from vanilla supcom ourselves?

**Comment by speed2CZ** [comment]
It was me who changed the game so vanilla is not needed anymore, together with distributing missing vanilla assets. So I'm pretty sure it's not needed.

**Pull request merged**
