### PR TITLE
#762 - fix - From chat user 'View Replays in Vault' doesn't show replays if rating <0 

### PR DESCRIPTION
**Pull request by ghost**
Subject : 
"I searched User Yucassha and it only showed one replay. (and not the one I just played against him)
After I set 'Min rating' to -100 the other replays (ladder rating below zero) showed up.
I would expect that chat user 'View Replays in Vault' shows all replays of a user."
Now when you start the client and look for a replay, it will have by default -2000, so all the replays will show when you search for an user.

Please check these boxes as you make your PR ready for merging:

Initial PR:

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by GrotheFAF** [comment]
This will not fix the subject problem, because of https://github.com/FAForever/client/blob/develop/src/chat/chatter.py#L476 starts searchVault with minrating=0.
(and isn't -2000 a bit much? only the bottom 100 in ladder rating go below -200)

**Comment by ghost** [comment]
Ugh, the replay vault can be based either on ladder rating if ladder1v1 or global rating otherwise. -2000 may be a bit too much but I don't know what is the minimal global/ladder rated player on faf so...

And I tried with "Yucassha" and it worked fine, I guess because the default value is now -2000 instead of 0 with this change. And for your line not really sure about it (was confused because you can precise minrating when you search replays, so it is not locked to 0)

**Comment by GrotheFAF** [comment]
You tried Yucassha" from Chat Lobby, right click user -> 'View Replay in Vault' ? (see subject) 
... which leads to the line.

**Comment by ghost** [comment]
Ahh ! Ok I didn't think of this case, good catch.

I searched Yucassha in the replay vault directly (which solved it) but right click on his name no I haven't tried it (and I guess for this one it is not solved).

**Comment by ghost** [comment]
Ok I fixed this case too when you look for the replays of the player with right click too, I lowered to -1400.
I read someone had -800 so I'm not that far from the truth. It should be fine now.

**Pull request merged**
