### PR TITLE
merge FriendList into develop

### PR DESCRIPTION
**Pull request by IDragonfire**
http://forums.faforever.com/forums/viewtopic.php?f=2&t=6794&start=20#p85200

* Added Format commit to clean up the unified diff

a "cleaner" version of #133 
closed #133

This PR is older then one year:
http://forums.faforever.com/forums/viewtopic.php?f=2&t=6794&start=20#p85200
https://bitbucket.org/visionik/modular-client/pull-request/32/friendlist/diff

### CODE REVIEW

**Comment by Sheeo** [comment]
Right, all travis builds are failing for this repo at the moment, for unknown reasons (Nothing that we changed set the wrong version of the Qt API).

This means I can't see coverage or test results, so I can't merge until this is working.

**Comment by IDragonfire** [comment]
What can I do to speed up the PR process?

**Comment by IDragonfire** [comment]
It tales some time, but original:
``27 files changed, 1878 insertions(+), 1067 deletions(-)`` 
and with the Format commit:
``27 files changed, 1186 insertions(+), 375 deletions(-)``

**Comment by IDragonfire** [comment]
I will now stop with force push to allow comments
Current Diff:
https://github.com/IDragonfire/lobby/compare/7626d2885512addce6293c90f27b35f7f680595b...IDragonfire:fb2f452d6df38ae0844af9283d5eb5bb7bda018d

**Comment by Sheeo** [comment]
Okay, I've had a look and the amount of code left to review is still massive.

It seems that this is about much more than just adding the friendlist, you also refactor administration and social commands into seperate classes. Could we reserve this for another pull request, so we can review and discuss such architecture changes in isolation?

**Comment by IDragonfire** [comment]
Correct, that is the reason I need this PR ...
I add global access points to avoid code duplication in the friendlist
Also mention in the Commit (and I am sure I talked about that in slack, but I know you where busy at this time)
`* added API for Admin, Client and Network Actions`

The problem is that rebasing of branches in the past with many conflicts and refactor is for me very hard ...

ClientAction: https://github.com/IDragonfire/lobby/commit/eecf623893d48d2e119fb3bb30119d2d8874d2ac
AdminAction:
https://github.com/IDragonfire/lobby/commit/9823e2385f33d136701549d77f206124003641d1
ServerPackages:
https://github.com/IDragonfire/lobby/commit/65a5ee8cfef49736f46d0a5fc35edee95f925ebb

Branch:
https://github.com/IDragonfire/lobby/commits/draft/model

How should I continue?

**Comment by IDragonfire** [comment]
My suggestion: I open a new PR with my draft/model branch, only for discussion, based on the commits?

**Comment by Sheeo** [comment]
It would have been better to seperate the work on the friendlist from the work of a network refactor in the first place -- that makes it easier to rebase.

Yes, please make a PR only containing the network-related commits, and then see if you can rebase your friendlist on top of develop.

**Comment by IDragonfire** [comment]
Model Discussion PR:
https://github.com/FAForever/client/pull/198

**Pull request closed without merging**
