### PR TITLE
Change the mod friend colour to something nice

### PR DESCRIPTION
**Pull request by HardlySoftly**

### CODE REVIEW

**Comment by VoRGoR** [comment]
+1

**Comment by ChrisKitching** [comment]
I kinda preferred the old blue colour. :P

**Comment by HardlySoftly** [comment]
Anyone who prefers the old blue colour can theme that in easily, anecdotally it didn't seem very popular.

**Comment by ChrisKitching** [comment]
Fair enough

Is there a popular theme we might want to adopt as default?

Are there other anecdotally popular ui tweaks we should do?

**Comment by HardlySoftly** [comment]
To my knowledge theming isn't very prevalent, although there are some UI tweaks I think people might like.

I've been asked a few times in the last week about providing support for coloured clan tags, maybe that's something we could look at?

**Comment by ChrisKitching** [comment]
> I've been asked a few times in the last week about providing support for coloured clan tags, maybe that's something we could look at?

Yes. Please do, I'll review and merge next week at the latest. That's a much-requested feature. There's also an old PR, I think.I forget what happened to it as I am only recently doing client development.

**Comment by ChrisKitching** [comment]
Rebased and merged here:
https://github.com/FAForever/client/commit/8e93adf94e4020115f2fda6d88d2c8d51d143aeb

Protip:
When merging changes from develop into your feature branch, use `git pull --rebase`. This avoids the creation of pointless remote-to-local merge commits like this second commit you have in this PR.

**Pull request closed without merging**
