### PR TITLE
#740 - Changed the icon of the unitdb tab to something more reasonable than …

### PR DESCRIPTION
**Pull request by FlyingThunder**
#740
…the twitch icon

took a scale/libra/however you call it because unit db kind of represents balance? (icon from https://icons8.de, its free to use for open source projects)

### CODE REVIEW

**Comment by Exotic-Retard** [comment]
in my theme which might become default at some point this would need fixing i.e. renaming the icon to the same thing as in that commit so it works. the theme is(?) shipped with the client atm so it needs to be maintained too. (not sure how mazor set it all up or what the plans are even for it.)

**Comment by Wesmania** [comment]
I'll make sure to fix that, once I do we'll merge this. Could you delete the old icon? I don't think it's used anywhere else and we can always restore it.

**Comment by FlyingThunder** [comment]
Ah, i kept it in because the "Streams" Tab might come back eventually, but sure

**Comment by Wesmania** [comment]
The hell, why did this close? Well, I'll merge it in anyway.

**Pull request closed without merging**
