### PR TITLE
fix text of ladder game warning

### PR DESCRIPTION
**Pull request by GrotheFAF**
removed 'them' because only one is waiting.

Initial PR:

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Wesmania** [comment]
I think 'they' can be a singular neutral pronoun in English, so it's at least correct here (don't know if unwieldy).

**Comment by GrotheFAF** [comment]
hmm, never heart of that. if you find me an example with 'them' in singular.

**Comment by duk3luk3** [comment]
Yeah, the "them" is perfectly fine there.

**Comment by GrotheFAF** [comment]
well, ok.

**Pull request closed without merging**
