### PR TITLE
Cleanup resize behaviour for client / channel

### PR DESCRIPTION
**Pull request by Wesmania**
I think there was once an attempt of optimization, with resize signals
from the client. Thet definitely don't work since the client eats a lot
of CPU while resized anyway, signals are only used in one place and
cause some timers to potentially get called a hundred times a second,
Let's clean this up and worry about resize performance some other day.

Signed-off-by: Igor Kotrasinski <ikotrasinsk@gmail.com>

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by GrotheFAF** [comment]
This changes startup chat tabs from:
Server / #aeolus / #..clan
to
Server / #...clan / #aeolus

this can be fixed in _chatwidget with:
L280 +        self.channels[channel] = newch
L287 +     else:

**Comment by Wesmania** [comment]
You're right - dammit, I missed that. I can see why it happens, I'll fix it in a follow-up PR.

**Comment by GrotheFAF** [comment]
and while you're at it...
in on_join 'channel' is the channel-name[string], in addChannel 'channel' is the channel-object.
That is confusing naming. (wonder why the code police let that fly...)
(and 'newch' .. what happen to 'new_channel', was that taken?-)

**Comment by Wesmania** [comment]
C naming habits, sorry. I'd rather not do renaming in commits that change logic, we can make some trivial rename / reorder PRs later.

**Pull request merged**
