### PR TITLE
Fix issue #883 : Fixing view aliases command which was broken

### PR DESCRIPTION
**Pull request by ghost**
Fixing the view aliases command which was broken (when you right click on an user in chat list and then click on view aliases, it was going to a broken url). I used to verify the result this jsfiddle : 
http://jsfiddle.net/qe84ejqc/6/

Please check these boxes as you make your PR ready for merging:

Initial PR:

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [x] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
Hi,

thank you for that contribution.

Like I mentioned in slack a few days ago, I am currently working on integrating the api. My code is in this branch: https://github.com/duk3luk3/client/tree/add-faf-api-support.

I will integrate your code into that, but it can't be merged into the client as-is. Using requests for blocking downloads is not good because it freezes the client while the download is running.

Feel free to make a PR to my client branch for this, or I can also integrate it myself.

Please coordinate PRs with me or @Wesmania (mazornoob on slack) to avoid duplicate work.

**Comment by ghost** [comment]
Hello,

That is fine and not really a waste of time(unless you were thinking of fixing this issue while integrating the api, then my bad :( ).

I can always adapt it to your code later (main logic is done and should work) if I just have to replace the requests by yours. 

And I didn't know about that for requests, that's good to know. I will look another time to see if I can make a PR to your client branch (not guaranteeing it).

**Comment by ghost** [comment]
This PR can be closed. I've adapted the code with the future api support so there is no reason to keep this one open. Did the PR over there : 
https://github.com/duk3luk3/client/pull/4

**Comment by Wesmania** [comment]
Alright.

**Pull request closed without merging**
