### PR TITLE
feature Mod dropdown list in Replays to show all mods (no more scrolling)

### PR DESCRIPTION
**Pull request by GrotheFAF**
set visibleItems to 50, so it will show all mods in List

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
This is a list of featured mods, isn't it? Wouldn't it be easier to just set the value to 100 statically?

**Comment by GrotheFAF** [comment]
yes. Set it to 50.
I didn't know that it would autoshrink to aktual mod number, but it does.

**Comment by duk3luk3** [comment]
Please rebase and add changelog message.

**Comment by GrotheFAF** [comment]
rebased and changelog added

**Pull request merged**
