### PR TITLE
fix for user in chat userlist shown in long gone games

### PR DESCRIPTION
**Pull request by GrotheFAF**
filter zombie games in client connection.py handle_game_info
workaround for #704 

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Wesmania** [comment]
Can you move this code to src/client/connection.py, class LobbyInfo, method handle_game_info? This way we'll be able to kill all messages about old 'playing' games at the source.

We're also merging this one for the next release.

**Comment by GrotheFAF** [comment]
done. 
(but it's not really 'at the source', just one function call earlier ;-)
(I used unused 'import config' for 'import time' hope you don't mind)

**Comment by Wesmania** [comment]
Cool, do the usual rebase & changelog & we'll merge it in (I guess we leave #704 open until we fix it on the server).

**Comment by GrotheFAF** [comment]
rebased and add changelog

**Pull request merged**
