### PR TITLE
Contribution instructions: Templates

### PR DESCRIPTION
**Pull request by duk3luk3**
* Adds Issue and PR templates

For #459

### CODE REVIEW

**Comment by duk3luk3** [comment]
@micheljung @Sheeo @Brutus5000 any feedback?

**Comment by micheljung** [comment]
I don't have strong feelings about this. Future will tell if it's good or not.

But the grammar in the last section needs to be fixed :P "Rebased onto develop" is not a task, "Remove this section" is.

**Comment by duk3luk3** [comment]
good catch, fixed.

**Comment by Brutus5000** [comment]
I had pushed my thoughts into the wiki months ago:
http://wiki.faforever.com/index.php?title=Bug_reporting_and_testing

**Comment by duk3luk3** [comment]
That link can be added to the readme.

**Pull request merged**
