### PR TITLE
Feature/hideprivategames

### PR DESCRIPTION
**Pull request by IDragonfire**
fixed #103
Add a little checkbox, that hide games with password (Hide Private Games)

before:
image

after:
image

### CODE REVIEW

**Comment by IDragonfire** [comment]
*push*

**Comment by JeroenDeDauw** [comment]
@IDragonfire needs manual rebase. Do you know how to do this?

**Comment by JeroenDeDauw** [comment]
Cool feature btw. What is the default value of the checkbox? And if I change the value, and then restart the application, will the change be kept or will it be back to the default?

**Comment by IDragonfire** [comment]
default is off
no settings
yes I can rebase ;)

Look on the Pr date xD

**Pull request closed without merging**
