### PR TITLE
Clean up whitespace with autopep8

### PR DESCRIPTION
**Pull request by Wesmania**
Signed-off-by: Igor Kotrasinski <ikotrasinsk@gmail.com>

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by GrotheFAF** [comment]
I guess this is obsolete after the refactor

**Comment by Wesmania** [comment]
It is, but it's just a matter of running autopep8 again and pushing the changes. We can do this any time with no effort, and I don't want to do this just yet to avoid impeding the ICE branch.

**Comment by ChrisKitching** [comment]
The problem with stuff like this is:
- It clobbers quite a bit of blame
- It will cause merge conflicts with almost all of the existing feature branches/PRs (of which there seem to be many)
- It doesn't really _achieve_ anything.

My suggestion would be to apply trivial formatting changes like this as you go along. When you touch a function, feel free to make its spaces "right" (having first agreed with everyone what arbitrary style rules we're using, so you don't end up in an edit war). This approach also has the advantage of avoiding the creation of a meaningless blame layer...

**Comment by Sheeo** [comment]
I concur, we've historically denied PR's which do this for the above reasons.

**Pull request closed without merging**
