### PR TITLE
Fix wrong channel order caused by 5a8ac3c4a1ec

### PR DESCRIPTION
**Pull request by Wesmania**
#748 accidentally changed chat tab order. This PR fixes it.

Signed-off-by: Igor Kotrasinski <ikotrasinsk@gmail.com>

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by GrotheFAF** [comment]
looks good and works as expected.   ... and found another problem - see below.
(and ignore my reverence above, just took your changes in for testing ;-)

(but you might change the PR-title: commit-Nr to fix-PR-Nr)

**Comment by GrotheFAF** [comment]
found another problem: 
Calling !smurfcheck [name] in #aeolus ->  adds TheSetoner channel  - with single-char width per line.
This is also true for joining a #clan channel
it's ok before this commit.

**Comment by Wesmania** [comment]
Seems hidden widgets don't have their size set, I pushed a fix for that. Setting text width when we're shown is probably the smartest, and makes sense since I don't even know if hidden widgets process resize events anyway.

**Comment by GrotheFAF** [comment]
that seems to do it... 
but...
if I click in Chat to change a channel, I get:
resizeEvent .. setTextWidth() - showEvent ..setTextWidth() - resizeEvent ..setTextWidth()
that is a lot of (setTextWidth())
- For testing I added a 'if self.isVisible():' before each setTextWidth(), I noticed on the above channel change, the first resizeEvent isVisible() is false, the subsequent showEvent and 2nd resizeEvent isVisible() is true.
But entering a new channel after !smurfcheck or /join, only has resizeEvent - showEvent (no 2nd resizeEvent), with the setTextWidth() in 1rst resizeEvent having no effect (isVisible being false)
so I guess that's how it is...
(resizeEvent  is also called on ladder-lure show and hide)
(and you lost the 'to no effect'-setTextWidth in addChannel, good ;-)
I asume now it's clearer what the timer was for, isn't it?-)
tricky... but this still looks better.

**Comment by Wesmania** [comment]
I don't think we should worry about resize events happening too often, I trust Qt to behave sanely in that regard, and it indeed seems to. If we ever need to throttle resize events, we'll do it properly.

**Pull request merged**
