### PR TITLE
Rename Find Games tab to Play

### PR DESCRIPTION
**Pull request by speed2CZ**

### CODE REVIEW

**Comment by HardlySoftly** [comment]
What's the reason for this?

**Comment by speed2CZ** [comment]
people that ask where can they host games

**Comment by HardlySoftly** [comment]
Right, although I don't necessarily think this will help.  Also it sort of implies that Coop tab doesn't mean the same thing as playing...

**Comment by speed2CZ** [comment]
Let's put it this way, I don't think it can make things worse. Also many people were suggesting this.

**Comment by HardlySoftly** [comment]
I think it would be best to merge the coop tab into the "Play" tab, and have one place for all game related things.

**Comment by speed2CZ** [comment]
And move coop leaderboards into leaderboard tab

**Pull request merged**
