### PR TITLE
remove unused label [subset]RankHint from gameswidget

### PR DESCRIPTION
**Pull request by GrotheFAF**
There are 2 RankHint labels with slightly different text, only one 'subsetRankHint' was used. I removed the the older unused "RankHint" and renamed 'subsetRankHint' to 'RankHint'.

- [ ] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Wesmania** [comment]
I like it. It sucks that designer is so git-unfriendly - it seems it randomly decided to remove a single space everywhere, replacing 600+ lines. I don't know if it'd be more of a pain to roll with a full replacement this once and clobber commit history, or to manually fix commits (doesn't seem especially bad in this case, we can script adding a single space everywhere).

**Comment by Wesmania** [comment]
I tested it a tiny bit - it seems the actual problem is that qt designer decided it likes 1-space indentations rather than 2-space ones,and that causes changes everywhere. I have absolutely no idea if it's configurable, or if our .ui files are even consistent about it. If it turns out we need to change that indentation, it might be best to split this commit into one that only changes indentation and one that makes meaningful changes.

**Comment by Wesmania** [comment]
I did some more checking - all the ui files except for this file use 1-space indents. We definitely want to bring it in line with the rest - maybe split the indent change to its own commit, so we can more easily see what meaningful changes are here. The indent thing is also worth putting on the wiki.

**Comment by Wesmania** [comment]
Rebase on develop (+ changelog), maybe add a separate commit just for indent change, and we'll merge it in.

**Comment by GrotheFAF** [comment]
rebased and add changelog

**Pull request merged**
