### PR TITLE
Move Settings Code into own class

### PR DESCRIPTION
**Pull request by IDragonfire**
This is as well a first step ...
I started with `_clientwindow.py` ...
settings are loaded everywhere in the codebase ....

Discoveries:
* https://github.com/FAForever/client/pull/250

### CODE REVIEW

**Comment by IDragonfire** [comment]
Maybe related to #72

**Comment by HardlySoftly** [comment]
Can we do this?

**Comment by Sheeo** [comment]
The persisted property class I added in config probably supercedes this PR. We need to make the rest of the things use it though.

**Comment by Sheeo** [comment]
With the changes to `config.Settings` I think we can close this. Thanks for your work :)

**Pull request closed without merging**
