### PR TITLE
#524 Use the new "News page"

### PR DESCRIPTION
**Pull request by micheljung**
And remove the _World Stopping_ "Download Client" button that confuses people

### CODE REVIEW

**Comment by duk3luk3** [comment]
You need to cherry-pick this commit: d71c3ff3cc55b8ba035a87b5ad733610bd3d22a4

you'll also need another one.

**Comment by duk3luk3** [comment]
Now you need to fixup runtests.py to set all the api's to version 2, like in the new runtests.py: https://github.com/FAForever/client/blob/develop/runtests.py

EDIT: Actually, the old runtests.py doesn't do any api setting at all... so no idea.

**Comment by duk3luk3** [comment]
Merged into `release/0.11.64`

**Comment by Wesmania** [comment]
The PR branch has some no longer used hotfix commits on top - I'll take the liberty to manually delete it.

**Pull request closed without merging**
