### PR TITLE
Make __main__.py a runnable-anywhere executable scipt

### LINKED ISSUE #550: Modify src/__main__.py so it can be run as linux executable
Making \_\_main\_\_.py a script (via a shebang) that's runnable anywhere greatly simplifies installation on Linux distros. The script can be automagically picked up by the build system (as it does on Gentoo, from which this change comes from) or can be simply copied anywhere and run directly.

### PR DESCRIPTION
**Pull request by Wesmania**
This closes #550 and makes installation of FAF on linux distros
much easier - now you can just copy over __main__ to $PATH rather
than make brittle scripts with hardcoded path to site-packages.

Signed-off-by: Igor Kotrasinski <ikotrasinsk@gmail.com>

Thank you for contributing to this project! Please set a good title for your PR and  replace this line with a (preferrably multi-line) description of your PR.

Please check these boxes as you make your PR ready for merging:

Initial PR:

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
> but really the best way to fix it would be to convert our imports to relative form.

Is there anything stopping us from doing that? Which imports specifically need to be fixed?

**Comment by Wesmania** [comment]
@duk3luk3 Pretty much everywhere where we import any local packages - thing like 'import util' and 'import config'. Changing these to 'from {.,..} import foo' would be one way of fixing it.
The logic in this patch is still useful for inclusion into a small script that only sets up path and calls a main method from the package (the way youtube-dl does it, for example) - it'd just require extracting all the logic from \_\_main\_\_.py into a function in \_\_init\_\_.

**Comment by Wesmania** [comment]
Now that I'm trying to do some relative imports, it seems much harder than I thought. I'd love to hear an opinion of someone more versed in Python, but I think adding the module to python path might be the more 'right' solution after all.

**Comment by duk3luk3** [comment]
Well it should just be installed as a proper module. I think we should put that on the list of things to do when we finally migrate to python 3.

**Pull request merged**
