### PR TITLE
Default game name when settings do not exist

### PR DESCRIPTION
**Pull request by madformuse**
When settings are cleared or client used for first time client.login is
not available early enough.

### CODE REVIEW

**Comment by ChrisKitching** [comment]
Try again with some commits ;)

**Comment by madformuse** [comment]
It did have some commits but I reset my fork because Sheeo doesn't want me to make it work but wants to solve the underlying state bug :p

**Comment by ChrisKitching** [comment]
Good choice :D

**Comment by ChrisKitching** [comment]
Get cracking! :D

**Comment by madformuse** [comment]
Yes sir :)

**Pull request closed without merging**
