### PR TITLE
feature - replace tab livestream with (old) unitdb

### PR DESCRIPTION
**Pull request by GrotheFAF**
with the new website the Livestreams-tab has a 404 - issue #534 
replacing it with a unitdb seems like a usefull reuse.

Please check these boxes as you make your PR ready for merging:

Initial PR:

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- ~[ ] Final commit includes "Fixes #issue" in commit message~

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [x] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
👍 

I'll test it asap

**Comment by duk3luk3** [comment]
Looks mostly good, two issues:

* Still has twitch icon in tab button
* Rendering problems: screenshot

Not sure if rendering can be fixed, might be issue with unitsdb...

**Comment by GrotheFAF** [comment]
I though about the icon, but why can't it be the unitdb icon? it's only for some time.
just declare the twitch icon to be the unidb icon, shall we?
The rendering (probably charset) has the same problems in  webbrowser.

**Comment by duk3luk3** [comment]
Fine by me, could you please add a changelog entry?

**Comment by GrotheFAF** [comment]
done. (hopefully to your pleasing)

**Comment by duk3luk3** [comment]
Thanks!

**Pull request merged**
