### PR TITLE
Fix #879 : spacing in the error message failed to get UID

### LINKED ISSUE #879: Bad spacing when getting "failed to calculate UID" error prompt
If you remove the faf-uid.exe in lib folder, you can see the message which has bad spacing by showing the br balise : 
https://i.imgur.com/pMOn1us.pn

### PR DESCRIPTION
**Pull request by ghost**
Fixed the error message "failed to get uid" which has bad spacing by showing a br balise and replaced it by a return to line. You can verify it by removing the faf-uid.exe in lib folder and see if it the error message is fixed.

Please check these boxes as you make your PR ready for merging:

Initial PR:

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Wesmania** [comment]
Please rebase and I'll merge.

**Comment by ghost** [comment]
No changelog? I guess whatever it is a really small fix.

**Comment by duk3luk3** [comment]
Please do add a changelog entry.

**Comment by Wesmania** [comment]
I took the liberty to rebase, I hope you don't mind :/

**Pull request merged**
