### PR TITLE
Switch secondary server to new dispatcher object

### LINKED ISSUE #683: Connection refactor broke reading messages from stats server
The connection refactor didn't catch that the stats / replay / secondary server used getattr to dispatch commands too. This should be fixed up.

### PR DESCRIPTION
**Pull request by Wesmania**
The connection refactor added a dispatcher object, but missed the fact
that SecondaryServer also used the getattr method. Pass the dispatcher
to the secondary server and use it to dispatch messages.

Fixes #683.

Signed-off-by: Igor Kotrasinski <ikotrasinsk@gmail.com>

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [x] Code is split into logical commits
- [ ] Code has tests
- [x] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
We need to merge this to fix regressions that already made it into develop, don't we? Please rebase and add changelog.

**Comment by Wesmania** [comment]
The regression happened within the version, I think we can do away with the changelog entry?

**Comment by GrotheFAF** [comment]
I tested it, works.

(and you can savely ignore the above references by me)

**Comment by duk3luk3** [comment]
Yes, if this wasn't released yet, no need for a changelog. I guess this can go in next?

**Comment by Wesmania** [comment]
As in "next to merge in", not "next" milestone? Sure.

**Pull request merged**
