### PR TITLE
make python functions lower case (in chat) fix #908

### LINKED ISSUE #908: internal affair - function naming
I see different functions - Qt, python - with the same name, that is confusing.

example: autoJoin in _clientwindow is a QtSignal, while _chatwidget it's a python function.

I would suggest to make python functions (and variabes) lower case, and keep the mixed case to Qt stuff.

### PR DESCRIPTION
**Pull request by GrotheFAF**
This is a suggestion to keep to the python convention (exampled on the chat dir).

Because, I see different functions - Qt, python - with the same name, that is confusing.

example: autoJoin in _clientwindow is a QtSignal, while in _chatwidget it's a python function.

I made the python functions lower case, and kept the mixed case to Qt stuff.

### CODE REVIEW

**Comment by Wesmania** [comment]
I'll go through these renames - I'm mostly worried that some of this stuff could also be in the UI files for classes, and they would have to be renamed as well.

**Comment by GrotheFAF** [comment]
I checked for not in .ui ... but maybe I missed something, so yes better checked twice.
(and if I missed some in .ui .. I would prefer to undo that rename)

**Comment by GrotheFAF** [comment]
coverage decreased -4.2% ... ? how so?

**Comment by Wesmania** [comment]
Hell if I know.

**Pull request merged**
