### PR TITLE
Fix instructions in README in order for FAF to find faf-uid on Linux

### PR DESCRIPTION
**Pull request by iczero**
FAF expects faf-uid to be in PATH

Initial PR: N/A, this is a PR to the readme

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by duk3luk3** [comment]
Thanks for your PR! I don't know if we'll merge your PR directly, @Wesmania might have something to say about paths.

**Comment by Wesmania** [comment]
Sounds OK, giving this one a +2.

**Comment by duk3luk3** [comment]
OK - @iczero please add a changelog entry if you want!

**Comment by iczero** [comment]
Does this really need a changelog entry? It's just modifying the readme to be a bit clearer.

**Pull request merged**
