### PR TITLE
Integrate Linux support for Lobby

### PR DESCRIPTION
**Pull request by Frozen-byte**
The changes I've made so far to get the Lobby running.
Currently the game is not startable but Client is made functional.

### CODE REVIEW

**Comment by Sheeo** [comment]
I will close this.

**Comment by JeroenDeDauw** [comment]
@Frozen-byte it's be very cool to have Linux support. Thanks for working on this. Will you be submitting a new PR?

**Comment by Frozen-byte** [comment]
Yes - currently my development is paused until the Servercode is stable. But I will definitely server native Linux support.

**Comment by Sheeo** [comment]
@Frozen-byte surely, you mean the client? :)

And yes, an update PR would be much apreciated.

**Comment by Frozen-byte** [comment]
I will make a new PR when the development on Lobby has begun.

**Pull request closed without merging**
