### PR TITLE
Move player logic

### PR DESCRIPTION
**Pull request by HardlySoftly**
Moves player logic (checking friends, colours etc) from _clientwindow.py to players.py

Also includes a fix for the colours bug in chat

### CODE REVIEW

**Comment by HardlySoftly** [comment]
Its mostly just moving code out of _clientwindow.py if it doesn't need to be there, its definitely a bloated class right now.

**Comment by IDragonfire** [comment]
Similiar idea to https://github.com/FAForever/client/pull/248

**Comment by Sheeo** [comment]
Please rebase this on latest develop so the CI checks can run. If you need any help do pm me :)

**Comment by HardlySoftly** [comment]
We need a git.txt https://www.xkcd.com/1597/

**Comment by Sheeo** [comment]
Seems you didn't get the rebase right -- the CI is failing due to import errors.

I'll fix it this time since I made the conflicting commits though. I'll note it here when merged :) Thanks for the contribution.

**Pull request closed without merging**
