### PR TITLE
feature - add subdirectory support to Local Archive

### PR DESCRIPTION
**Pull request by GrotheFAF**
+ Sub directories in the local replays folder will be listed each as directory item.
Doubleclick one of the subfolders will show the content of that subfolder as current replay folder.
If the current folder is a sub folder (not util.REPLAY_DIR) a 'directory up' item '..' is added. A doubleclick will show the parent folder again as current replay folder.
+ Folders will not be reread on Tab reentry if nothing has changed (using folders mtime).
+ Replays with missing Dates get an seperate Bucket 'date missing'. (untested, I have none of those ;-)

- [x] PR branch should be named `issuenum`-`fix`/`feature`/`cleanup`-`description`
- [ ] Code is split into logical commits
- [ ] Code has tests
- [ ] Final commit includes "Fixes #issue" in commit message

When all builds pass and a maintainer is happy with your PR, the "ready" label will be applied. Please complete these tasks then:

- [ ] Rebase onto develop
- [ ] Add changelog entry
- [ ] Remove this entire template section

### CODE REVIEW

**Comment by Wesmania** [comment]
I tried it out, I like the idea. Moving around folders is a little bit confusing, since the ".." element is in a submenu. It'd be great if we just had a separate icon for directories - we could just put all the directories above all the other buckets, with optional '..' as the first position (like in file managers, we see '..', then  directories, then files).

**Comment by GrotheFAF** [comment]
I changed it. 
(but you won't like my sorting trick ;-)

**Comment by Wesmania** [comment]
That's one way to do that. I like the flat model. I think this is pull ready, maybe with a different dir icon. After ICE™ probably.

**Comment by GrotheFAF** [comment]
If you really like flat, why not process #500 ?-)
The folder icons are from XP Explorer, I don't know what ICE™ is. hint please.

**Comment by Wesmania** [comment]
The ICE adapter, major PRs will go in after it's integrated.

**Comment by GrotheFAF** [comment]
Oh, that ICE. Tested and ready?
(but that you consider this PR 'major', makes me laugh. It's tiny.)
I have so much stuff in the pipeline to PR .. but my curent PRs are already stuck .. so WTF?

**Comment by Wesmania** [comment]
Talk to @duk3luk3 about it. I have some PRs queued too, I just have some additional branches on top of those. It does make sense IMO given that ICE is a big feature to add.

**Comment by duk3luk3** [comment]
* What's the license of these icons? We can't pull things that aren't under a compatible free license into a GPL project.
* Is this something users want?

**Comment by GrotheFAF** [comment]
exchanged the icons with GPL once .. and in black.

**Comment by GrotheFAF** [comment]
and what about this, delete it?

**Pull request closed without merging**
