### PR TITLE
Improving Mod Vault Searching

### PR DESCRIPTION
**Pull request by CodingSquirrel**
We no longer do a local search when typing in the search input box.
We now search when you press enter in the search input box.

### CODE REVIEW

**Comment by ChrisKitching** [comment]
:D

**Comment by ChrisKitching** [comment]
... That was probably the right branch. Sheeo? I think develop is "crazy new-patcher land" for now?

**Comment by Sheeo** [comment]
Yes that's fine.

I would prefer we also clean up the localSearch function, which is (presumably?) no longer used.

Bonus points for implementing google-like instant search ;)

**Comment by CodingSquirrel** [comment]
I removed the localSearch function. I'm not quite sure what you mean.

**Comment by Sheeo** [comment]
I skimmed the code a bit too fast and missed the negative diff removing the function, sorry!

**Pull request merged**
